"""End-to-end UI verification in real Chrome (Playwright). Prints PASS/FAIL per check; screenshots -> data/shots/verify_*.png"""
import sys, time, json, os, calendar
sys.path.insert(0, "scripts")
from pw import launch
from playwright.sync_api import sync_playwright
from PIL import Image

URL = os.environ.get("APP_URL", "http://127.0.0.1:8765/index.html")
SH = "data/shots/verify_"
res = []


def ok(name, cond, info=""):
    res.append((name, bool(cond), str(info)))
    print(("PASS " if cond else "FAIL ") + name + (("  - " + str(info)) if info != "" else ""), flush=True)


def S(page, expr):
    return page.evaluate(expr)


def boot(page):
    page.goto(URL)
    page.wait_for_function("window.__booted===true", timeout=60000)
    time.sleep(1.5)


def set_iso(page, s, utc=True):
    page.click('#zoneSeg button[data-z="%s"]' % ("utc" if utc else "local"))
    page.fill("#tmISO", s)
    page.press("#tmISO", "Enter")
    time.sleep(0.4)


def tms(page):
    return S(page, "window.__app.S.t")


def utc(y, mo, d, h=0, mi=0, s=0):
    return calendar.timegm((y, mo, d, h, mi, s)) * 1000


def text(page, sel):
    return S(page, "document.querySelector('%s').innerText.replace(/\\n/g,' ')" % sel)


with sync_playwright() as p:
    b, ctx, page, logs = launch(p, w=1440, h=900)
    boot(page)
    errs = [l for l in logs if l.startswith("[error]") or l.startswith("[pageerror]")]
    ok("A1 boots with no console errors / page errors", not errs, errs[:3])
    warns = [l for l in logs if l.startswith("[warning]")]
    ok("A2 no WebGL shader warnings", not warns, warns[:2])
    ok("A3 WebGL2 + logarithmic depth buffer", S(page, "window.__app.renderer.capabilities.isWebGL2 && window.__app.renderer.capabilities.logarithmicDepthBuffer"))
    # ---- B views
    for v in ["system", "earthmoon", "planet", "sky"]:
        S(page, "window.__app.setView('%s',{reaim:true})" % v)
        time.sleep(3.0 if v != "sky" else 2.0)
        page.screenshot(path=SH + "view_%s.png" % v)
        im = Image.open(SH + "view_%s.png" % v).convert("L").resize((96, 60))
        px = list(im.getdata())
        mean = sum(px) / len(px)
        var = sum((x - mean) ** 2 for x in px) / len(px)
        ok("B view '%s' renders (non-blank)" % v, var > 4, "variance %.1f" % var)
    # ---- C geocoding for 3 places
    S(page, "window.__app.setView('system')")
    for q, tzx, key in [("Tokyo", "Asia/Tokyo", "Tokyo"), ("Sydney", "Australia/Sydney", "Sydney"), ("Madrid", "Europe/Madrid", "Madrid")]:
        page.fill("#q", q)
        page.wait_for_selector("#sugg div[data-i]", timeout=15000)
        time.sleep(0.3)
        n = page.locator("#sugg div[data-i]").count()
        page.locator("#sugg div[data-i]").first.click()
        time.sleep(0.8)
        L = json.loads(S(page, "JSON.stringify(window.__app.S.loc)"))
        ok("C geocode '%s' -> place + IANA tz %s" % (q, tzx), key in L["name"] and L["tz"] == tzx, "%s | %s | %d suggestions" % (L["name"], L["tz"], n))
        page.wait_for_function("document.querySelector('#wxBody').innerText.includes('Humidity') || document.querySelector('#wxBody').innerText.toLowerCase().includes('unavailable')", timeout=25000)
        txt = text(page, "#wxBody")
        ok("C weather card for %s" % q, "Humidity" in txt, txt[:90])
        S(page, "window.__app.setView('sky',{reaim:true})")
        time.sleep(1.2)
        page.screenshot(path=SH + "sky_%s.png" % key)
        sa = S(page, "JSON.stringify({sun:window.__app.SKY.info.sunAlt,L:window.__app.SKY.info.L})")
        ok("C sky view for %s computed" % q, "sun" in sa, sa)
        S(page, "window.__app.setView('system')")
        time.sleep(0.5)
    # ---- D picker typing / E steps (UTC mode for exact arithmetic)
    set_iso(page, "1969-07-20 20:17:00")
    ok("D ISO typing '1969-07-20 20:17:00' (UTC)", tms(page) == utc(1969, 7, 20, 20, 17, 0), tms(page))
    ok("D mode flips to TIME TRAVEL", (not S(page, "window.__app.S.live")) and "TIME TRAVEL" in S(page, "document.getElementById('badge').textContent"))
    ok("D banner visible", S(page, "getComputedStyle(document.getElementById('banner')).display") == "flex")
    page.fill("#tmISO", "2023-02-30 10:00:00")
    page.press("#tmISO", "Enter")
    time.sleep(0.3)
    ok("D invalid date '2023-02-30' rejected (field flagged, time unchanged)", S(page, "document.getElementById('tmISO').classList.contains('bad')") and tms(page) == utc(1969, 7, 20, 20, 17, 0))
    set_iso(page, "0999-01-01 00:00:00")
    ok("D year 999 rejected with explanation", tms(page) == utc(1969, 7, 20, 20, 17, 0) and "1000" in S(page, "document.getElementById('toast').textContent"), S(page, "document.getElementById('toast').textContent")[:70])
    set_iso(page, "2024-02-28 12:00:00")
    page.click("#stepsFwd button:nth-child(3)")
    ok("E +1 day across leap day -> 2024-02-29", tms(page) == utc(2024, 2, 29, 12), tms(page))
    page.click("#stepsFwd button:nth-child(6)")
    ok("E +1 year from Feb 29 -> Feb 28 (clamped)", tms(page) == utc(2025, 2, 28, 12), tms(page))
    set_iso(page, "2024-12-31 23:59:00")
    page.click("#stepsFwd button:nth-child(1)")
    ok("E year-end rollover 23:59 +1 min -> 2025-01-01 00:00", tms(page) == utc(2025, 1, 1, 0, 0), tms(page))
    set_iso(page, "2024-01-31 08:00:00")
    page.click("#stepsFwd button:nth-child(5)")
    ok("E +1 month from Jan 31 -> Feb 29 (clamped)", tms(page) == utc(2024, 2, 29, 8), tms(page))
    set_iso(page, "2024-01-01 00:00:00")
    page.click("#stepsFwd button:nth-child(7)")
    ok("E +1 synodic month = +29.5306 d", abs(tms(page) - utc(2024, 1, 1) - 29.530588853 * 86400000) < 1000)
    page.click("#stepsBack button:nth-child(1)")
    ok("E -1 synodic month round trip", tms(page) == utc(2024, 1, 1))
    # ---- G DST (New York)
    S(page, "window.__app.setLocation({name:'New York, NY, USA',lat:40.7128,lon:-74.006,elev:10,tz:'America/New_York'},{silent:true})")
    page.click('#zoneSeg button[data-z="local"]')
    page.fill("#tmISO", "2024-03-10 02:30:00")
    page.press("#tmISO", "Enter")
    time.sleep(0.4)
    t = tms(page)
    ok("G NY 2024-03-10 02:30 (non-existent) -> moved to 03:30 EDT = 07:30Z", t == utc(2024, 3, 10, 7, 30), t)
    ok("G DST-gap explained to user", "does not exist" in S(page, "document.getElementById('toast').textContent"))
    page.fill("#tmISO", "2024-03-10 01:30:00")
    page.press("#tmISO", "Enter")
    time.sleep(0.3)
    page.click("#stepsFwd button:nth-child(2)")
    ok("G +1 hour across spring-forward lands on 03:30 EDT (07:30Z)", tms(page) == utc(2024, 3, 10, 7, 30), tms(page))
    page.fill("#tmISO", "2024-11-03 01:30:00")
    page.press("#tmISO", "Enter")
    time.sleep(0.3)
    ok("G fall-back ambiguity resolves to first 01:30 (EDT = 05:30Z)", tms(page) == utc(2024, 11, 3, 5, 30), tms(page))
    ok("G UTC offset shown beside local time", "UTC" in text(page, "#clkOff"), text(page, "#clkOff"))
    page.fill("#tmDate", "2020-05-17")
    page.press("#tmDate", "Tab")
    time.sleep(0.3)
    ok("D native date input applies (location time)", "2020-05-17" in text(page, "#clkLocal"), text(page, "#clkLocal"))
    # ---- I scrubber drag / zoom
    t0 = tms(page)
    box = page.locator("#tlwrap").bounding_box()
    page.mouse.move(box["x"] + box["width"] / 2, box["y"] + 30)
    page.mouse.down()
    page.mouse.move(box["x"] + box["width"] / 2 - 300, box["y"] + 30, steps=8)
    page.mouse.up()
    time.sleep(0.4)
    t1 = tms(page)
    ok("I timeline drag scrubs time (~+6 d of the 30-day span)", 4 * 86400000 < t1 - t0 < 9 * 86400000, "%.2f d" % ((t1 - t0) / 86400000))
    page.mouse.move(box["x"] + box["width"] / 2, box["y"] + 30)
    for _ in range(4):
        page.mouse.wheel(0, 300)
    time.sleep(0.4)
    span = S(page, "window.__app.TL.span") / 86400000
    ok("I wheel zooms the timeline out (span grows)", span > 30, "%.0f d" % span)
    for _ in range(60):
        page.mouse.wheel(0, 400)
    time.sleep(0.4)
    span = S(page, "window.__app.TL.span") / 86400000 / 365.2425
    ok("I zoom capped at 500 years", 499 < span <= 500.1, "%.1f y" % span)
    time.sleep(0.5)
    ne = S(page, "window.__app.TL.events.filter(e=>e.type==='solar'||e.type==='lunar').length")
    ok("I 500-year timeline shows eclipse markers instantly (precomputed table)", ne > 1500, "%d eclipse markers" % ne)
    page.screenshot(path=SH + "timeline_500y.png")
    for _ in range(60):
        page.mouse.wheel(0, -400)
    time.sleep(0.3)
    ok("I zoom floor 1 day", abs(S(page, "window.__app.TL.span") / 86400000 - 1) < 0.01)
    page.mouse.dblclick(box["x"] + 100, box["y"] + 30)
    time.sleep(0.3)
    # ---- v1.1 features
    S(page, "window.__app.setView('planet'); window.__app.focusBody('Earth',{dur:10})"); time.sleep(2)
    ok("V1 relief normal map + live cloud grid active", S(page, "!!window.__app.OB.Earth.mat.defines.HAS_NORMAL") and S(page, "window.__app.CLOUD.target") == 1 or "Earth clouds" in text(page, "#cloudNote"), text(page, "#cloudNote"))
    ok("V2 bloom pipeline available", S(page, "window.__app.POST.ok"))
    pm = S(page, "(()=>{const a=window.__app;const s=a.STARS.reduce((p,q)=>q[2]<p[2]?q:p);const d0=a.starDirAt(s,0),d1=a.starDirAt(s,974);const c=Math.acos(Math.min(1,d0[0]*d1[0]+d0[1]*d1[1]+d0[2]*d1[2]))*180/Math.PI;return c})()")
    ok("V3 proper motion: Sirius moves ~0.36 deg over 974 yr", 0.33 < pm < 0.39, "%.3f deg" % pm)
    # ---- J URL hash
    set_iso(page, "2024-04-08 18:42:37")
    S(page, "window.__app.setView('sky',{reaim:true})")
    time.sleep(1.0)
    page.click("#btnCopy")
    time.sleep(0.6)
    url = S(page, "location.href")
    h = S(page, "location.hash")
    ok("J share link encodes loc, t, view", "loc=" in h and "t=2024-04-08T18:42:37Z" in h and "view=sky" in h, h[:130])
    p2 = ctx.new_page()
    p2.goto(url)
    p2.wait_for_function("window.__booted===true", timeout=60000)
    time.sleep(2)
    st2 = json.loads(p2.evaluate("JSON.stringify({t:window.__app.S.t,view:window.__app.S.view,live:window.__app.S.live,name:window.__app.S.loc.name})"))
    ok("J hash restores time, view and place in a fresh page", st2["t"] == utc(2024, 4, 8, 18, 42, 37) and st2["view"] == "sky" and not st2["live"], st2)
    p2.close()
    # ---- K return to now
    page.click("#btnNow")
    time.sleep(0.4)
    ok("K 'Now' returns to the LIVE clock", S(page, "window.__app.S.live") and abs(tms(page) - time.time() * 1000) < 3000 and "LIVE" in S(page, "document.getElementById('badge').textContent"))
    # ---- L weather: past vs future
    S(page, "window.__app.setLocation({name:'Dallas, Texas, USA',lat:32.7767,lon:-96.797,elev:131,tz:'America/Chicago'},{silent:true})")
    set_iso(page, "2024-04-08 18:00:00")
    page.wait_for_function("document.getElementById('wxSrc').innerText.includes('Historical')", timeout=25000)
    wx = text(page, "#wxBody")
    ok("L past date uses archive data, labelled 'Historical (ERA5 reanalysis)'", "Historical" in text(page, "#wxSrc") and "Cloud cover" in wx, wx[:100])
    page.screenshot(path=SH + "past_weather.png")
    fut = time.gmtime(time.time() + 365 * 86400)
    set_iso(page, "%04d-%02d-%02d 12:00:00" % (fut.tm_year, fut.tm_mon, fut.tm_mday))
    page.wait_for_function("document.getElementById('wxBody').innerText.includes('No forecast')", timeout=30000)
    ok("L +1 year: 'No forecast available' + labelled climatology", "Climatology" in text(page, "#wxBody"), text(page, "#wxBody")[:120])
    set_iso(page, "1935-06-01 12:00:00")
    page.wait_for_function("document.getElementById('wxBody').innerText.includes('1940')", timeout=15000)
    ok("L before 1940: 'No weather data'", True, text(page, "#wxBody")[:50])
    # ---- event jump
    set_iso(page, "2026-09-30 12:00:00")
    page.select_option("#evSel", "solar-any")
    page.click("#evNext")
    time.sleep(1.5)
    ok("M event jump: next solar eclipse after 2026-09-30 = 2027-02-06", abs(tms(page) - utc(2027, 2, 6, 15, 59)) < 3 * 3600000, S(page, "new Date(window.__app.S.t).toISOString()"))
    page.click("#evPrev")
    time.sleep(1.5)
    ok("M event jump: previous solar eclipse = 2026-08-12", abs(tms(page) - utc(2026, 8, 12, 17, 45)) < 3 * 3600000, S(page, "new Date(window.__app.S.t).toISOString()"))
    page.select_option("#evSel", "fullMoon")
    page.click("#evNext")
    time.sleep(0.8)
    ok("M event jump: next full moon (2026-08-28)", abs(tms(page) - utc(2026, 8, 28, 4, 18)) < 6 * 3600000, S(page, "new Date(window.__app.S.t).toISOString()"))
    page.select_option("#preSel", "e2024")
    time.sleep(2.0)
    ok("M preset 2024 total eclipse -> Dallas at totality", abs(tms(page) - utc(2024, 4, 8, 18, 42, 37)) < 5000 and "Dallas" in S(page, "window.__app.S.loc.name"), S(page, "new Date(window.__app.S.t).toISOString()"))
    page.screenshot(path=SH + "preset_2024.png")
    ok("M eclipse card shows TOTALITY", "TOTALITY" in text(page, "#eclBody"))
    page.click("#btnFinder")
    page.wait_for_selector("#fTbl tr[data-ms]", timeout=30000)
    n = page.locator("#fTbl tr[data-ms]").count()
    ok("M eclipse finder lists eclipses within +-10 y", n > 25, "%d rows" % n)
    page.screenshot(path=SH + "finder.png")
    page.keyboard.press("Escape")
    # ---- self test
    page.click("#btnAbout")
    page.click("#btnTests")
    time.sleep(1.5)
    sm = text(page, "#testSum")
    ok("N in-app self-tests (round-trips, DST, 1582, leap years, eclipses)", "all" in sm and "passed" in sm, sm)
    page.screenshot(path=SH + "about.png")
    page.keyboard.press("Escape")
    # ---- tour
    S(page, "window.__app.goLive()")
    page.click("#btnTour")
    time.sleep(6.5)
    page.screenshot(path=SH + "tour.png")
    ok("O cinematic tour runs (letterbox + caption)", S(page, "getComputedStyle(document.getElementById('bars')).display") == "block" and len(S(page, "document.getElementById('cap').textContent")) > 5, S(page, "document.getElementById('cap').textContent"))
    page.click("#btnTour")
    time.sleep(0.5)
    # ---- FPS
    S(page, "window.__app.setView('system')")
    time.sleep(4)
    S(page, "window.__prof()")
    time.sleep(5)
    f1 = S(page, "window.__prof()")
    ok("P FPS, solar-system view (Intel HD 4600, 1440x900)", f1["fps"] > 28, "%.0f fps @ dpr %.2f, %d draw calls, %d tris" % (f1["fps"], f1["dpr"], f1["calls"], f1["tris"]))
    S(page, "window.__app.setView('planet'); window.__app.focusBody('Earth',{dur:10})")
    time.sleep(3)
    S(page, "window.__prof()")
    time.sleep(5)
    f2 = S(page, "window.__prof()")
    ok("P FPS, Earth close-up", f2["fps"] > 28, "%.0f fps @ dpr %.2f" % (f2["fps"], f2["dpr"]))
    S(page, "window.__app.setSpeed(864000)")
    time.sleep(2.5)
    page.screenshot(path=SH + "playback_10d.png")
    sb = S(page, "window.__app.S.spinBlend")
    ok("P 10 days/s playback fades the Earth spin (spinBlend -> 0)", sb < 0.2, "spinBlend=%.3f" % sb)
    S(page, "window.__app.goLive()")
    b.close()
    # ---- failure paths: offline Open-Meteo
    b, ctx, page, logs = launch(p, w=1440, h=900)
    ctx.route("**/*open-meteo.com/**", lambda r: r.abort())
    boot(page)
    ok("Q offline weather/geocode: app still boots", S(page, "window.__booted===true"))
    page.fill("#q", "Paris")
    page.wait_for_function("document.getElementById('sugg').innerText.toLowerCase().includes('unavailable')", timeout=15000)
    ok("Q failed geocode shows a message, no crash", True, S(page, "document.getElementById('sugg').innerText")[:60])
    page.wait_for_function("document.getElementById('wxBody').innerText.toLowerCase().includes('unavailable')", timeout=20000)
    ok("Q weather failure shows 'unavailable', UI keeps working", True, text(page, "#wxBody")[:70])
    S(page, "window.__app.setView('sky',{reaim:true})")
    time.sleep(1.5)
    ok("Q sky view works without network", S(page, "window.__app.SKY.info.sunAlt !== undefined"))
    page.screenshot(path=SH + "offline.png")
    errs = [l for l in logs if l.startswith("[pageerror]")]
    ok("Q no uncaught exceptions while offline", not errs, errs[:2])
    b.close()
    # ---- CDN library failure
    b, ctx, page, logs = launch(p, w=1000, h=700)
    ctx.route("**/three.module.js", lambda r: r.abort())
    page.goto(URL)
    time.sleep(14)
    msg = S(page, "(document.querySelector('#loading')||{innerText:''}).innerText")
    ok("R missing library -> loading screen explains (no blank page)", "loading" in msg.lower() or "could not" in msg.lower(), msg[:80])
    b.close()
    # ---- mobile
    b, ctx, page, logs = launch(p, w=390, h=844, dpr=2)
    boot(page)
    time.sleep(2)
    page.screenshot(path=SH + "mobile.png")
    sw = S(page, "document.scrollingElement.scrollWidth")
    ok("S mobile 390px: no horizontal page scroll", sw <= 392, sw)
    page.click("#mnL")
    time.sleep(0.5)
    page.screenshot(path=SH + "mobile_panel.png")
    page.click("#mnR")
    time.sleep(0.5)
    page.screenshot(path=SH + "mobile_panel2.png")
    ok("S mobile panels open as sheets", S(page, "getComputedStyle(document.getElementById('pRight')).display") == "block")
    b.close()

sz = os.path.getsize("site/index.html") / 1048576
ok("T final file size <= 16 MB", sz <= 16, "%.2f MB" % sz)
bad = [r for r in res if not r[1]]
print("\n%d/%d checks passed" % (len(res) - len(bad), len(res)))
for r in bad:
    print("FAILED:", r[0], r[2])
json.dump(res, open("data/verify_results.json", "w"), indent=1)
